name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: click-me
          - os: macos-latest
            asset_name: click-me
          - os: windows-latest
            asset_name: click-me.exe

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: mac - install simple-http-server
      if: matrix.os == 'macos-latest'
      run: |
        cargo install simple-http-server --root http-server-vendor/http-server-macos --no-track
        mv http-server-vendor/bin/simple-http-server http-server-vendor/http-server-macos

    - run: ls -R http-server-vendor

    - name: Build
      run: cargo b

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: click-me-${{ runner.os }}
        path: target/debug/${{ matrix.asset_name }}
